services:

  # P2Pool Service
  p2pool:
    image: ghcr.io/rodrigomaia06/p2pool-docker:latest  # Latest P2Pool image
    container_name: p2pool  # Container name
    privileged: true  # Required for access to system features like hugepages
    restart: unless-stopped  # Auto-restart unless manually stopped
    depends_on:
      - monerod  # Ensure Monero node is running first
    ports:
      - "18333:18333"  # P2Pool worker connection port
      - "37888:37888"  # P2Pool Mini Network P2P port
    volumes:
      - ./p2pool/:/home/p2pool/.p2pool:rw  # Persist data
      - /dev/hugepages:/dev/hugepages:rw  # Optimized memory (hugepages)
    command: >  # Start P2Pool with custom options
      --host monerod  # Monero node address
      --local-api  # Enable local API
      --data-api /home/p2pool/.p2pool  # Data storage path
      --rpc-port 18081  # Monero RPC port
      --wallet YOUR_XMR_ADDRESS  # Replace with your Monero wallet address
      --p2p 0.0.0.0:37888  # P2P port
      --stratum 0.0.0.0:18333  # Stratum port
      --mini  # Enable Mini mode

  # P2Pool Statistics Service
  p2pool-statistics:
    image: ghcr.io/rodrigomaia06/p2pool-docker-statistics:latest  # Latest statistics image
    container_name: p2pool-statistics  # Container name
    restart: unless-stopped  # Auto-restart unless manually stopped
    depends_on:
      - p2pool  # Wait for P2Pool to be ready
    volumes:
      - ./p2pool:/data:ro  # Mount P2Pool data as read-only for stats
