name: Docker Build P2Pool
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Runs every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Latest P2Pool Commit Hash
      id: get_commit
      run: |
        commit=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/SChernykh/p2pool/releases/latest | jq -r '.tag_name' | cut -c 2-)
        echo "LATEST_TAG=$commit" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile_P2Pool --tag ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
        docker tag ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }} ghcr.io/${{ github.repository }}:latest
        
    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
        docker push ghcr.io/${{ github.repository }}:latest
