name: Docker Build

on:
  schedule:
    - cron: '0 0 * * 0'  # Build both images every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Latest P2Pool Commit Hash
      id: get_commit
      run: |
        commit=$(curl -s https://api.github.com/repos/SChernykh/p2pool/releases/latest | jq -r '.tag_name' | cut -c 2-)
        echo "LATEST_TAG=$commit" >> $GITHUB_ENV

    - name: Build & Push P2Pool Node Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
        docker tag ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }} ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
        docker push ghcr.io/${{ github.repository }}:latest

    - name: Build & Push Statistics Image
      run: |
        docker build ./statistics --file ./statistics/Dockerfile --tag ghcr.io/${{ github.repository }}-statistics:${{ env.LATEST_TAG }}
        docker tag ghcr.io/${{ github.repository }}-statistics:${{ env.LATEST_TAG }} ghcr.io/${{ github.repository }}-statistics:latest
        docker push ghcr.io/${{ github.repository }}-statistics:${{ env.LATEST_TAG }}
        docker push ghcr.io/${{ github.repository }}-statistics:latest
